import AppleLogo from '@/icons/ic-apple-logo.svg';
import PlayLogo from '@/icons/ic-play-logo.svg';
import CalendarCheck from '@/icons/ic-calendar-check.svg';
import Horoscope from '@/icons/ic-horoscope.svg';
import PeopleCircle from '@/icons/ic-people-circle.svg';
import Streams from '@/icons/ic-streams.svg';
import AppleLogoFill from '@/icons/ic-apple-logo-fill.svg';
import FacebookLogo from '@/icons/ic-facebook-logo.svg';
import GoogleLogo from '@/icons/ic-google-logo.svg';
import LogoFilledGradient from '@/icons/ic-logo-filled-gradient.svg';
import LogoFilled from '@/icons/ic-logo-filled.svg';
import PlayButton from '@/icons/ic-play-button.svg';
import PauseButton from '@/icons/ic-pause-button.svg';
import PhoneButton from '@/icons/ic-phone-button.svg';
import AvatarCircle from '@/icons/ic-avatar-circle.svg';
import VideoCircle from '@/icons/ic-video-circle.svg';
import Coin from '@/icons/ic-coin.svg';
import Globe from '@/icons/ic-globe.svg';
import Headphones from '@/icons/ic-headphones.svg';
import MobilePhone from '@/icons/ic-mobile-phone.svg';
import Cards from '@/icons/ic-cards.svg';
import Meditation from '@/icons/ic-meditation.svg';
import Numerology from '@/icons/ic-numerology.svg';
import FacebookColored from '@/icons/ic-facebook-colored.svg';
import InstagramColored from '@/icons/ic-instagram-colored.svg';
import YoutubeColored from '@/icons/ic-youtube-colored.svg';
import Surprise from '@/icons/present.svg';
export const IconAppleLogo = AppleLogo as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconPlayLogo = PlayLogo as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconCalendarCheck = CalendarCheck as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconHoroscope = Horoscope as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconPeopleCircle = PeopleCircle as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconStreams = Streams as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconAppleLogoFill = AppleLogoFill as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconFacebookLogo = FacebookLogo as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconGoogleLogo = GoogleLogo as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconLogoFilledGradient = LogoFilledGradient as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconLogoFilled = LogoFilled as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconPlayButton = PlayButton as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconPauseButton = PauseButton as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconPhoneButton = PhoneButton as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconAvatarCircle = AvatarCircle as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconVideoCircle = VideoCircle as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconCoin = Coin as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconGlobe = Globe as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconHeadphones = Headphones as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconMobilePhone = MobilePhone as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconCards = Cards as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconMeditation = Meditation as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconNumerology = Numerology as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconFacebookColored = FacebookColored as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconInstagramColored = InstagramColored as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconYoutubeColored = YoutubeColored as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
export const IconSurprise = Surprise as (props: React.SVGProps<SVGSVGElement>) => JSX.Element;
